image:
  - Visual Studio 2019

configuration:
  - Release

for:

-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - cinst --allow-empty-checksums smlnj
      
  build_script:
    - deploy\win\build-64.bat
  
