#!/bin/bash

set -eu

case $(git status --porcelain --untracked-files=no) in
    "") ;;
    *) echo "ERROR: Current working copy has been modified - not proceeding"; exit 2;;
esac

mkdir -p packages
echo

. deploy/metadata.sh

if [ -d /Applications ]; then
    
    echo "Proceed to rebuild, package, and sign version $version [Yn] ? "
    read yn
    case "$yn" in "") ;; [Yy]) ;; *) exit 3;; esac
    echo "Proceeding"

    ./repoint install

    deploy/osx/build-and-package.sh "$version"

else

    echo -n "Proceed to rebuild and package version $version [Yn] ? "
    read yn
    case "$yn" in "") ;; [Yy]) ;; *) exit 3;; esac
    echo "Proceeding"

    ./deploy/linux/build-and-test-appimage.sh

    squashedversion=$(echo "$version" | sed 's/_-//g')

    current=$(git rev-parse --short HEAD)

    dir="sonic-annotator-$version-linux64-static"

    (
        cd deploy/linux/docker/output
        mkdir -p "$dir"
        cp SonicAnnotator-"$current"-x86_64.AppImage "$dir/sonic-annotator"
        chmod +x "$dir/sonic-annotator"
        cp ../../../../README.md "$dir"
        cp ../../../../CHANGELOG "$dir"
        cp ../../../../COPYING "$dir"
        cp ../../../../CITATION "$dir"
        tar cvzf "$dir.tar.gz" "$dir"
        rm -rf "$dir"
    )

    mv deploy/linux/docker/output/"$dir".tar.gz packages/

fi

echo "Done"

