#!/bin/bash

set -eu

case $(git status --porcelain --untracked-files=no) in
    "") ;;
    *) echo "ERROR: Current working copy has been modified - not proceeding"; exit 2;;
esac

mkdir -p packages
echo

. deploy/metadata.sh

if [ -d /Applications ]; then
    
    qtdir="/Users/cannam/Qt/6.7.2/macos"

    echo "Proceed to rebuild, package, and sign version $version using"
    echo -n "Qt path \"$qtdir\" [Yn] ? "
    read yn
    case "$yn" in "") ;; [Yy]) ;; *) exit 3;; esac
    echo "Proceeding"

    ./repoint install

    builddir="build"

    arch=arm64
    
    rm -rf "$builddir"
    PATH="$qtdir/bin:$PATH" arch -$arch meson setup "$builddir" --cross-file=deploy/cross/macos-$arch.txt --buildtype release
    ninja -C "$builddir"

    deploy/osx/sign.sh "$builddir"/sonic-annotator
    deploy/osx/notarize.sh "$builddir"/sonic-annotator

    dir="sonic-annotator-$version-macos"
    mkdir -p "$dir"
    cp "$builddir"/sonic-annotator "$dir/"
    cp README.md CHANGELOG COPYING CITATION "$dir/"
    tar cvzf "$dir.tar.gz" "$dir"
    rm -rf "$dir"

    mv "$dir.tar.gz" packages/

else

    echo -n "Proceed to rebuild and package version $version [Yn] ? "
    read yn
    case "$yn" in "") ;; [Yy]) ;; *) exit 3;; esac
    echo "Proceeding"

    ./deploy/linux/build-and-test-appimage.sh

    squashedversion=$(echo "$version" | sed 's/_-//g')

    current=$(git rev-parse --short HEAD)

    dir="sonic-annotator-$version-linux64-static"

    (
        cd deploy/linux/docker/output
        mkdir -p "$dir"
        cp SonicAnnotator-"$current"-x86_64.AppImage "$dir/sonic-annotator"
        chmod +x "$dir/sonic-annotator"
        cp ../../../../README.md "$dir"
        cp ../../../../CHANGELOG "$dir"
        cp ../../../../COPYING "$dir"
        cp ../../../../CITATION "$dir"
        tar cvzf "$dir.tar.gz" "$dir"
        rm -rf "$dir"
    )

    mv deploy/linux/docker/output/"$dir".tar.gz packages/

fi

echo "Done"

