# Note 22.04 was the first LTS with Qt6
FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y \
    software-properties-common \
    build-essential \
    libbz2-dev \
    libfftw3-dev \
    libfishsound1-dev \
    libid3tag0-dev \
    liblo-dev \
    liblrdf0-dev \
    libmad0-dev \
    liboggz2-dev \
    libopus-dev \
    libopusfile-dev \
    libpulse-dev \
    libasound2-dev \
    libjack-dev \
    libsamplerate-dev \
    libsndfile-dev \
    libsord-dev \
    libxml2-utils \
    qt6-base-dev \
    qt6-pdf-dev \
    qt6-base-dev-tools \
    libqt6svg6-dev \
    libgl1-mesa-dev \
    raptor2-utils \
    librubberband-dev \
    yajl-tools \
    git \
    mercurial \
    curl wget \
    unzip \
    smlnj \
    autoconf \
    automake \
    libtool \
    lintian \
    ninja-build \
    libglib2.0-dev \
    python3-pip

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git config --global http.postBuffer 4M

WORKDIR /root
RUN pip3 install meson

COPY id_rsa_build .ssh/id_rsa_build
COPY known_hosts .ssh/known_hosts
RUN chmod 600 .ssh/id_rsa_build .ssh/known_hosts
RUN echo '{"accounts": {"sourcehut": "~breakfastquay"}}' > .repoint.json
RUN ( echo '[ui]' ; echo 'ssh = ssh -i /root/.ssh/id_rsa_build' ) > .hgrc

# The explicit revision number here is to make sure the following git
# clone is not cached from a different revision
RUN echo Cloning revision [[REVISION]]

RUN git clone https://github.com/sonic-visualiser/sonic-annotator
WORKDIR sonic-annotator
RUN git checkout [[REVISION]]

RUN ./repoint install
RUN meson setup build --buildtype release
RUN ninja -C build

RUN deploy/linux/deploy-appimage.sh
RUN cp build/sonic-annotator .
RUN tar cvf output-appimage.tar sonic-annotator *.AppImage && cp output-appimage.tar /tmp/
